package toolkit.generate;

public class GenerateTypeTableFile {

        private void generateMybatis(String tableName, String sqlSuffix, String annotation) {
                StringBuilder sb = new StringBuilder();
                sb.append("        <!-- " + annotation + " -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("        <insert id = \"insert" + sqlSuffix + "\" parameterType = \"java.util.HashMap\">");
                sb.append(System.getProperty("line.separator"));
                sb.append("                <![CDATA[insert into `" + tableName + "` (`name`, `description`) values (#{name}, #{description})]]>");
                sb.append(System.getProperty("line.separator"));
                sb.append("        </insert>");
                sb.append(System.getProperty("line.separator"));
                sb.append("        <delete id = \"delete" + sqlSuffix + "\" parameterType = \"java.util.HashMap\">");
                sb.append(System.getProperty("line.separator"));
                sb.append("                <![CDATA[delete from `" + tableName + "`]]>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                <where>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <if test = \"null != id\">");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <![CDATA[and `id` = #{id}]]>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        </if>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                </where>");
                sb.append(System.getProperty("line.separator"));
                sb.append("        </delete>");
                sb.append(System.getProperty("line.separator"));
                sb.append("        <update id = \"update" + sqlSuffix + "\" parameterType = \"java.util.HashMap\">");
                sb.append(System.getProperty("line.separator"));
                sb.append("                <![CDATA[update `" + tableName + "`]]>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                <set>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <if test = \"null != name\">");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <![CDATA[`name` = #{name},]]>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        </if>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <if test = \"null != description\">");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <![CDATA[`description` = #{description},]]>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        </if>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <if test = \"'set_null' == description\">");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <![CDATA[`description` = null,]]>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        </if>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                </set>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                <where>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <if test = \"null != id\">");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <![CDATA[and `id` = #{id}]]>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        </if>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                </where>");
                sb.append(System.getProperty("line.separator"));
                sb.append("        </update>");
                sb.append(System.getProperty("line.separator"));
                sb.append("        <select id = \"select" + sqlSuffix + "\" parameterType = \"java.util.HashMap\" resultType = \"java.util.HashMap\">");
                sb.append(System.getProperty("line.separator"));
                sb.append("                <![CDATA[select * from `" + tableName + "`]]>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                <where>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <if test = \"null != id\">");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <![CDATA[and `id` = #{id}]]>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        </if>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <if test = \"null != ne_id\">");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <![CDATA[and `id` != #{ne_id}]]>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        </if>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <if test = \"null != name\">");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <![CDATA[and `name` = #{name}]]>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        </if>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                </where>");
                sb.append(System.getProperty("line.separator"));
                sb.append("        </select>");
                System.out.println(sb.toString());
        }

        private void generateDispatch(String moduleName, String sqlSuffix, String annotation) {
                StringBuilder sb = new StringBuilder();
                sb.append("                <servlet>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <!-- 名称: 添加" + annotation + " -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <servletName>add" + sqlSuffix + "</servletName>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <sdboType>transaction</sdboType>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <namespace>non-select,select" + sqlSuffix + ":name;insert,insert" + sqlSuffix + ":name,description</namespace>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <permission>" + moduleName + "_add" + sqlSuffix + "</permission>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <parameters>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <!-- " + annotation + "名称（2-32个汉字、字符或数字） -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <name>name</name>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <type>string</type>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <format>^[\\u4e00-\\u9fffa0-9a-zA-Z]{2,32}$</format>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <isNull>false</isNull>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                </parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <!-- " + annotation + "描述（2-64个汉字、字符或数字） -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <name>description</name>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <type>string</type>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <format>^[\\u4e00-\\u9fffa0-9a-zA-Z]{2,64}$</format>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <isNull>true</isNull>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                </parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        </parameters>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                </servlet>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                <servlet>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <!-- 名称: 删除" + annotation + " -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <servletName>remove" + sqlSuffix + "</servletName>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <sdboType>delete</sdboType>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <namespace>delete" + sqlSuffix + "</namespace>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <permission>" + moduleName + "_remove" + sqlSuffix + "</permission>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <parameters>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <!-- 编号（大于等于1的数字） -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <name>id</name>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <type>integer</type>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <format>^[1-9]+[0-9]*$</format>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <isNull>false</isNull>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                </parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        </parameters>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                </servlet>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                <servlet>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <!-- 名称: 修改" + annotation + " -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <servletName>modify" + sqlSuffix + "</servletName>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <sdboType>transaction</sdboType>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <namespace>non-select,select" + sqlSuffix + ":id->ne_id,name;update,update" + sqlSuffix + ":id,name,description</namespace>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <permission>" + moduleName + "_modify" + sqlSuffix + "</permission>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <parameters>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <!-- 编号（大于等于1的数字） -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <name>id</name>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <type>integer</type>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <format>^[1-9]+[0-9]*$</format>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <isNull>false</isNull>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                </parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <!-- " + annotation + "名称（2-32个汉字、字符或数字） -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <name>name</name>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <type>string</type>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <format>^[\\u4e00-\\u9fffa0-9a-zA-Z]{2,32}$</format>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <isNull>false</isNull>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                </parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <!-- " + annotation + "描述（2-64个汉字、字符或数字） -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <name>description</name>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <type>string</type>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <format>^[\\u4e00-\\u9fffa0-9a-zA-Z]{2,64}$</format>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <isNull>true</isNull>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                </parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        </parameters>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                </servlet>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                <servlet>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <!-- 名称: 获取" + annotation + " -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <servletName>get" + sqlSuffix + "</servletName>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <sdboType>select</sdboType>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <namespace>select" + sqlSuffix + "</namespace>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <permission>" + moduleName + "_get" + sqlSuffix + "</permission>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        <parameters>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <!-- 编号（大于等于1的数字） -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <name>id</name>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <type>integer</type>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <format>^[1-9]+[0-9]*$</format>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <isNull>true</isNull>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                </parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                <parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <!-- " + annotation + "名称（2-32个汉字、字符或数字） -->");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <name>name</name>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <type>string</type>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <format>^[\\u4e00-\\u9fffa0-9a-zA-Z]{2,32}$</format>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                        <isNull>true</isNull>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                                </parameter>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                        </parameters>");
                sb.append(System.getProperty("line.separator"));
                sb.append("                </servlet>");
                System.out.println(sb.toString());
        }

        public GenerateTypeTableFile() {
                String tableName = "erp_enterprise-cost-journal-account";
                String moduleName = "erp";
                String sqlSuffix = "EnterpriseCostJournalAccount";
                String annotation = "企业成本流水账";
                this.generateMybatis(tableName, sqlSuffix, annotation);
                this.generateDispatch(moduleName, sqlSuffix, annotation);
        }

        public static void main(String args[]) {
                new GenerateTypeTableFile();
        }
}